# Generated by Django 4.2.15 on 2024-10-08 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_registrant_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='accommodation',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, verbose_name='Do you need Accomodation'),
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.registrant')),
            ],
        ),
    ]
