# Generated by Django 5.1.3 on 2024-12-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0005_alter_inhouse_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="Minister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="inhouse",
            name="department",
            field=models.CharField(
                choices=[
                    ("ushering", "Ushering"),
                    ("sanctuary", "Sanctuary"),
                    ("spirit & Truth", "Spirit & Truth"),
                    ("technical", "Technical"),
                    ("light & Power", "Light & Power"),
                    ("media", "New Wine Media"),
                    ("follow up", "Labour Room (follow_up)"),
                    ("decoration", "Decoration"),
                    ("welfare", "Taste & See"),
                    ("pastoral", "Pastoral Care"),
                    ("pastor", "Pastor"),
                    ("special Guest", "Special Guest"),
                ],
                max_length=25,
            ),
        ),
    ]
