# Generated by Django 5.1.3 on 2024-12-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0006_minister_alter_inhouse_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="minister",
            name="qr_code",
            field=models.ImageField(blank=True, upload_to="qrcodes/"),
        ),
    ]
