# Generated by Django 5.1.3 on 2024-12-15 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0007_minister_qr_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrant",
            name="qr_code",
        ),
    ]
