# Generated by Django 5.1.3 on 2024-12-15 10:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0008_remove_registrant_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrant",
            name="uid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
